sudo: false
dist: trusty

language: php

notifications:
  email: false

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.3
  - 7.2
  - 7.1

env:
  matrix:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=nightly WP_MULTISITE=0
  - WP_VERSION=nightly WP_MULTISITE=1
  global:
    - PATH="$TRAVIS_BUILD_DIR/vendor/bin:$HOME/.composer/vendor/bin:$PATH"
    - WP_CLI_BIN_DIR="$TRAVIS_BUILD_DIR/vendor/bin"

before_install:
  - |
    # Remove Xdebug for a huge performance increase:
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
install:
  - composer install
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

before_script:
  - composer validate

script: composer test

jobs:
  fast_finish: true
  include:
    - stage: lint
      script:
        - composer lint
    - stage: coverage
      before_install: skip
      script:
        - composer test -- --coverage-clover=coverage.xml
      after_script:
        - bash <(curl -s https://codecov.io/bash)

stages:
  - lint
  - test
  - coverage
  - deploy
