name: Lint

on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@2.11.0
        with:
          php-version: "7.4"
          coverage: none
          tools: composer, cs2pr

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache PHP dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install PHP dependencies
        run: |
          composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
          echo "${PWD}/vendor/bin" >> $GITHUB_PATH

      - name: Lint files
        run: phpcs -q --report=checkstyle | cs2pr
